name: Dependabot Auto Merge

on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: 'squash and merge'
          target: minor
          approve: true
