name: Code CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --prefer-offline

      # Build first to avoid broken monorepo dependencies
      - name: Build
        run: yarn build
        
      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:ci

      - name: Publish to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
