name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish'
        required: true

jobs:
  publish:
    name: Publish ${{ github.event.inputs.package }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './packages/${{ github.event.inputs.package }}/'

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      # Build first to avoid broken monorepo dependencies
      - name: Build
        run: pnpm build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
