name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish'
        required: true

jobs:
  publish:
    name: Publish ${{ github.event.inputs.package }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './packages/${{ github.event.inputs.package }}/'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --prefer-offline

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
