name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish'
        required: true

jobs:
  publish:
    name: Publish ${{ github.event.inputs.package }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './packages/${{ github.event.inputs.package }}/'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install packages
        run: yarn install

      # Build first to avoid broken monorepo dependencies
      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
