name: Release Flow

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: write # Required to create a release PR
  checks: write # Required to create a check run
  issues: write # Required to create issues

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    environment:
      name: NPM Registry

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/actions/checkout/issues/1471
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci-version
          commit: 'chore: update versions'
          title: 'Release plan'

          # https://github.com/changesets/action/issues/246
          # https://github.com/changesets/changesets/pull/674
          publish: pnpm ci-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
